"""
Django settings for moiru project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

from decouple import config, Csv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS é puxado do .env
# No servidor, o .env deve ter: ALLOWED_HOSTS=127.0.0.1,localhost,osadm.umj.edu.br,10.10.12.62
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    
    # Mantenha APENAS esta linha para o app tasks:
    'tasks.apps.TasksConfig', 
    
    'crispy_forms',
    'crispy_bootstrap5',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tasks.middleware.RequestUserMiddleware',
    'moiru.middleware.ForcePasswordChangeMiddleware',
]

ROOT_URLCONF = 'moiru.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'moiru.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- REDIRECIONAMENTOS DE LOGIN ---
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# --- MÍDIA (UPLOADS) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- SESSÃO (LEMBRAR-ME) ---
# A sessão expira ao fechar o navegador por padrão.
# A view customizada de login altera isso se o usuário marcar o checkbox.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ==============================================================================
# CONFIGURAÇÕES CRÍTICAS PARA REDE INTERNA (INTRANET / HTTP)
# ==============================================================================

# Permite cookies de login sem HTTPS (Necessário para rodar no IP da rede)
CSRF_COOKIE_SECURE = None
SESSION_COOKIE_SECURE = None

# Lista de origens confiáveis para o formulário de login (CSRF)
# OBRIGATÓRIO incluir protocolo (http://) e porta (:8000) se não for padrão
CSRF_TRUSTED_ORIGINS = [
    'http://osadm.umj.edu.br',
    'http://osadm.umj.edu.br:8000',
    'http://10.10.12.62',
    'http://10.10.12.62:8000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# settings.py

# ==========================================
# CONFIGURAÇÃO DE E-MAIL (SMTP GMAIL)
# ==========================================

# Define o backend como SMTP (envio real)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Configurações do Servidor do Gmail
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # Gmail exige criptografia TLS

# Puxa o usuário e a senha do arquivo .env (Segurança)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

# O nome que aparecerá como remetente para quem receber o e-mail
DEFAULT_FROM_EMAIL = 'Sistema Moiru <moiru.system@gmail.com>'

# Adicione isso no final do settings.py

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuração do WhiteNoise para servir arquivos comprimidos e com cache
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
