# Generated by Django 6.0.1 on 2026-02-12 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Ação')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='Identificador')),
                ('color', models.CharField(help_text='Código Hexadecimal', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Ambiente',
                'verbose_name_plural': 'Categorias de Ambiente',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Departamento')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='Identificador')),
                ('color', models.CharField(help_text='Código Hexadecimal (ex: #FF0000)', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Item')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='Identificador')),
                ('color', models.CharField(help_text='Código Hexadecimal', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Ocupação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Ocupação',
                'verbose_name_plural': 'Tipos de Ocupação',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Status')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='Identificador')),
                ('color', models.CharField(help_text='Cor representativa (CSS Hex)', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Unidade')),
                ('identifier', models.SlugField(unique=True, verbose_name='Sigla')),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('C', 'Criou'), ('U', 'Editou'), ('D', 'Excluiu')], max_length=1)),
                ('model_name', models.CharField(max_length=100, verbose_name='Tabela')),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(max_length=255, verbose_name='Item')),
                ('history', models.JSONField(blank=True, null=True, verbose_name='Mudanças Detalhadas')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='Identificador (Sala)')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Ocupação')),
                ('block', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bloco')),
                ('floor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Andar')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ponto de Referência')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environments', to='tasks.category', verbose_name='Categoria Macro')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='tasks.unit', verbose_name='Unidade (Sede)')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['unit', 'block', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título/Assunto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/attachments/', verbose_name='Anexo (Legado)')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Término')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.action', verbose_name='Ação')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.department', verbose_name='Departamento')),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.environment', verbose_name='Ambiente')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('responsibles', models.ManyToManyField(blank=True, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tasks.status')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.unit', verbose_name='Unidade')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/followups/', verbose_name='Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('new_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_novo', to='tasks.status')),
                ('old_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_anterior', to='tasks.status')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='tasks.ticket', verbose_name='Chamado')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tickets/attachments/', verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.ticket')),
            ],
        ),
    ]
