# Generated by Django 6.0.1 on 2026-02-12 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Selecione o item relacionado a este chamado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.item', verbose_name='Item / Equipamento'),
        ),
    ]
