# Generated by Django 6.0.1 on 2026-02-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_ticket_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Setor / Departamento', 'verbose_name_plural': 'Setores / Departamentos'},
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Setor'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone / Ramal'),
        ),
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Código Hexadecimal (ex: #FF0000)', max_length=7),
        ),
        migrations.AlterField(
            model_name='department',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='Identificador (Sigla)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Setor'),
        ),
    ]
