# Generated by Django 6.0.1 on 2026-03-02 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_department_options_department_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matrícula')),
                ('contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato (Telefone/Celular)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Informação Adicional de Usuário',
                'verbose_name_plural': 'Informações Adicionais de Usuários',
            },
        ),
    ]
