# Generated by Django 6.0.1 on 2026-03-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='force_password_change',
            field=models.BooleanField(default=True, verbose_name='Exige troca de senha'),
        ),
    ]
