# Generated by Django 6.0.1 on 2026-03-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_userinfo_force_password_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
    ]
