# Generated by Django 6.0.1 on 2026-03-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_item_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='color',
        ),
    ]
